server:
  port: 8761

eureka:
  client:
  #表示是否将自己注册到Eureka Server上，默认为true，由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
    registerWithEureka: false
    #由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false，表示是否从Eureka Server上获取注册信息，默认为true
    fetchRegistry: false
  server:
    enableSelfPreservation: false