##dev：本地环境；prd测试环境
spring:
  profiles:
      active: dev
  application:
    name: tqf-escloudurl

server:
  port: 9094

esindex: "tqf-test-es"
estype: "testtype"

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

